name: Docs

on:
  push:
    branches: [master]

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    env:
      working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build Website
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build
